Repository tscircuit/tscircuit.com, pull requests merged in 2025-04, with the labels that each got.

#798 resolve Dashboard title issue
  .gitignore
  src/pages/dashboard.tsx
  src/pages/view-package.tsx
Labels: 🙋 Bounty claim

#804 Don't show schematic/pcb/3d view buttons if they aren't available for a package
  src/components/ViewPackagePage/components/mobile-sidebar.tsx
  src/components/ViewPackagePage/components/preview-image-squares.tsx
  src/hooks/use-preview-images.ts
Labels: 🙋 Bounty claim

#813 feat(routing): add 404 page and handle not found states
  src/App.tsx
  src/pages/404.tsx
  src/pages/view-package.tsx
Labels: enhancement

#818 feat: when json not avail, blank out the tabs
  src/components/ViewPackagePage/components/main-content-view-selector.tsx
Labels: 🙋 Bounty claim

#814 feat: add trending page to display popular snippets
  src/App.tsx
  src/components/Footer.tsx
  src/components/SnippetCard.tsx
  src/pages/trending.tsx
  src/pages/user-profile.tsx
Labels: 🙋 Bounty claim

#823 feat(package-details): add license management to package details dialog
  fake-snippets-api/lib/db/schema.ts
  src/components/ViewPackagePage/components/mobile-sidebar.tsx
  src/components/ViewPackagePage/components/repo-page-content.tsx
  src/components/ViewPackagePage/components/sidebar-about-section.tsx
  src/components/ViewPackagePage/components/sidebar.tsx
  src/components/ViewPackagePage/utils/get-license-content.ts
  src/components/dialogs/edit-package-details-dialog.tsx
  src/hooks/use-package-details-form.ts
  src/lib/getLicenseFromLicenseContent.ts
Labels: 🙋 Bounty claim

#879 Added file selector to /p/editor
  src/components/package-port/CodeEditor.tsx
  src/components/package-port/CodeEditorHeader.tsx
Labels: 🙋 Bounty claim

#891 refactor(CodeEditorHeader): add support for several file types formatting
  src/components/package-port/CodeEditorHeader.tsx
  src/lib/utils/load-prettier.ts
Labels: 🙋 Bounty claim

#895 refactor(CodeEditor): support tscircuit.config.json && extract file selection logic into utility function
  src/components/ViewPackagePage/utils/is-hidden-file.ts
  src/components/package-port/CodeAndPreview.tsx
  src/components/package-port/CodeEditor.tsx
  src/lib/utils/findTargetFile.ts
Labels: 🙋 Bounty claim

#904 fix tscircuit.com/search
  src/components/PageSearchComponent.tsx
  src/components/SearchComponent.tsx
  src/pages/search.tsx
Labels: 🙋 Bounty claim

#928 Fix the overflow and tooltip ui when hovering over code components
  src/components/CodeEditor.tsx
  src/components/package-port/CodeEditor.tsx
Labels: 🙋 Bounty claim

#926 feat: Add star timestamp to snippets and update related logic
  fake-snippets-api/lib/db/schema.ts
  fake-snippets-api/routes/api/packages/add_star.ts
  fake-snippets-api/routes/api/packages/list.ts
  fake-snippets-api/routes/api/snippets/list.ts
  src/pages/user-profile.tsx
Labels: 🙋 Bounty claim

#934 Added syntax highlighting to the hover tooltip in code editor
  src/components/CodeEditor.tsx
  src/hooks/use-shiki-highlighter.ts
  src/index.css
Labels: 🙋 Bounty claim

#922 feature: Settings view now allows changing visibility and deleting the package
  fake-snippets-api/routes/api/packages/update.ts
  src/components/ViewPackagePage/components/mobile-sidebar.tsx
  src/components/ViewPackagePage/components/sidebar-about-section.tsx
  src/components/dialogs/edit-package-details-dialog.tsx
  src/hooks/use-package-details-form.ts
Labels: 🙋 Bounty claim, 💰 Rewarded

#950 fix: readme code syntax highlight
  fake-snippets-api/routes/api/order_quotes/create.ts
  src/components/ViewPackagePage/components/markdown-viewer.tsx
  src/index.css
Labels: 🙋 Bounty claim

#963 commented ai chat box and added snippetcard to show snippets on /dashboard
  src/pages/dashboard.tsx
Labels: 🙋 Bounty claim

#955 If a user goes to /dashboard, show them an empty state that tells them to login
  src/pages/dashboard.tsx
Labels: 🙋 Bounty claim

#956 feat: add manual edit conflict warning handling
  bun.lock
  package.json
  src/components/package-port/CodeAndPreview.tsx
  src/hooks/use-toast.tsx
  src/lib/utils/informManualEditConflicts.tsx
Labels: 🙋 Bounty claim

#976 fix: removed fork from own package
  src/components/ViewPackagePage/components/package-header.tsx
Labels: 🙋 Bounty claim

#978 fix(CodeEditor): ensure consistent path handling in fsMap
  src/components/package-port/CodeEditor.tsx
Labels: 🙋 Bounty claim

#979 fixed ctrl/cmd prompt regression
  src/components/CodeEditor.tsx
Labels: 🙋 Bounty claim
