Repository tscircuit/tscircuit.com, pull requests merged in 2025-05, with the labels that each got.

#985 fixed rendering of double boards
  src/components/CodeAndPreview.tsx
  src/components/package-port/CodeAndPreview.tsx
Labels: 🙋 Bounty claim, stale

#1007 simplified fsMap that would be passed to runframe
  src/components/CodeAndPreview.tsx
  src/components/package-port/CodeAndPreview.tsx
Labels: 💎 Bounty, $10

#1084 fix: dialog (dropdown) remains visible during navigation
  src/components/ViewPackagePage/components/main-content-header.tsx
Labels: 🙋 Bounty claim, 💰 Rewarded

#1079 fix: jlcpcb part already imported
  src/components/JLCPCBImportDialog.tsx
Labels: 🙋 Bounty claim

#1161 feat!: add default view functionality to package updates and create tests for validation
  bun-tests/fake-snippets-api/routes/packages/update.test.ts
  fake-snippets-api/lib/db/schema.ts
  fake-snippets-api/routes/api/packages/create.ts
  fake-snippets-api/routes/api/packages/update.ts
  src/components/ViewPackagePage/components/mobile-sidebar.tsx
  src/components/ViewPackagePage/components/repo-page-content.tsx
  src/components/ViewPackagePage/components/sidebar-about-section.tsx
  src/components/dialogs/edit-package-details-dialog.tsx
  src/hooks/use-package-details-form.ts
  src/index.css
Labels: major

#1170 feat: restrict access to private packages based on user session
  fake-snippets-api/routes/api/packages/get.ts
  src/pages/package-editor.tsx
  src/pages/view-package.tsx
Labels: stale
