Repository tscircuit/tscircuit.com, pull requests merged in 2025-03, with the labels that each got.

#708 fix: Ensure isStarred state updates when snippet changes
  src/components/ViewSnippetHeader.tsx
Labels: 🙋 Bounty claim

#716 feat(profile): add starred snippets tab to user profile
  playwright-tests/profile-page.spec.ts
  playwright-tests/snapshots/profile-page.spec.ts-profile-page-snippets-tab.png
  playwright-tests/snapshots/profile-page.spec.ts-profile-page-starred-tab.png
  playwright-tests/snapshots/profile-page.spec.ts-snippet-page-open-after-star-click.png
  src/pages/user-profile.tsx
Labels: 🙋 Bounty claim, stale

#750 Improved bad alignment of packages page
  package.json
  src/components/SnippetTypeIcon.tsx
  src/pages/user-profile.tsx
Labels: 🙋 Bounty claim

#757 changed "Snippets" to "Packages" and used the correct "timeago" package
  bun.lock
  package.json
  playwright-tests/profile-page.spec.ts
  src/pages/user-profile.tsx
Labels: 🙋 Bounty claim

#754 db debugger for fake
  fake-snippets-api/routes/api/_fake/db.ts
Labels: stale

#765 feat: add page title and image tag
  bun.lock
  package.json
  src/ContextProviders.tsx
  src/pages/editor.tsx
  src/pages/view-snippet.tsx
Labels: 🙋 Bounty claim, 💰 Rewarded

#776 Added fallback for broken images
  public/assets/fallback-image.svg
  src/components/OptimizedImage.tsx
Labels: 🙋 Bounty claim
